services:
  - type: web
    name: pdf-chatbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port 10000 --server.enableCORS false
    envVars:
      - key: PORT
        value: 10000
